name: guess_the_word
description: Guess the Word

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.7
  shared_preferences: ^2.0.11
  google_fonts: ^2.3.1
  sqflite: 2.0.0+3
  intl: 0.17.0
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/images/logo1.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
     - family: Baloo
       fonts:
         - asset: assets/fonts/BalooDa2-Regular.ttf
         - asset: assets/fonts/BalooDa2-Bold.ttf
         - asset: assets/fonts/BalooDa2-Medium.ttf
     - family: Sans
       fonts:
         - asset: assets/fonts/ProductSans-Regular.ttf
         - asset: assets/fonts/ProductSans-Italic.ttf
           style: italic
         - asset: assets/fonts/ProductSans-Bold.ttf
           weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
